### ISSUE TITLE
Json Tree Grid Layout Format

### ISSUE THREAD

**Issue by attran1** [dmackdev/egui_json_tree#41]
Hello,

Do you have an example showing how to display data in a json tree grid layout?

Anthony

**Comment by dmackdev** [comment]
Hi, I am not sure exactly what you mean - could you please clarify?

If you mean showing a JSON tree _within_ a grid, you can see an example of this on my other project: [pubsubman](https://github.com/dmackdev/pubsubman):

- [Here](https://github.com/dmackdev/pubsubman/blob/master/media/messages_view_search.png) is a screenshot of how the JSON tree looks within an `egui::Grid` - you can also see the grid row expands to accommodate the JSON tree when it has expanded elements.
- [Here](https://github.com/dmackdev/pubsubman/blob/8dbeb4b71211d4a12f1437c513aa4123e4308734/pubsubman/src/ui/messages_view.rs#L225-L277) is the corresponding code for the above.

**Comment by attran1** [comment]
Hi,  

I don't know how to insert image with Github.  Here is a link that shows an example of it https://www.htmlelements.com/docs/grid-tree-grid/.  The idea is to present more than 1 field for each leaf of the tree.

Anthony

**Comment by dmackdev** [comment]
If you want something to look like a tree grid like in your link, I think `egui::Grid` would be a more suitable choice.

**Comment by attran1** [comment]
thank you.  I started a new thread in egui to request for help.
